version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - ${ENV_IP_NGINX}:${ENV_PORT_NGINX}:80
    volumes:
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/data
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./
      dockerfile: config/docker/php/dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/data
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: percona:5.7
    ports:
      - ${ENV_PORT_MYSQL}:3306
    tty: true
    restart: always
    volumes:
      - ./var/docker_data/mysql:/var/lib/mysql
    env_file:
      - .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    networks:
      - app-network

  redis:
    image: redis:5.0.3-alpine
    volumes:
      - ./var/docker_data/redis/data:/data
    ports:
      - ${ENV_PORT_REDIS}:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
