version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_IP}:${NGINX_PORT}:80
      - 443:443
    volumes:
      - ./config/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/docker/nginx/localhost.crt:/etc/nginx/conf.d/localhost.crt
      - ./config/docker/nginx/localhost.key:/etc/nginx/conf.d/localhost.key
      - .:/data
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./
      dockerfile: config/docker/php/dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/data
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: percona:5.7
    ports:
        - ${MYSQL_PORT}:3306
    tty: true
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
    env_file:
      - .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    networks:
      - app-network

  redis:
      image: redis:5.0.3-alpine
      volumes:
          - redis-data:/data
      ports:
          - ${REDIS_PORT}:6379
      networks:
          - app-network

volumes:
    mysql-data:
    redis-data:

networks:
    app-network:
        driver: bridge
